server:
  port: 8083

spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/inventory_db}
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

inventory:
  concurrency:
    unsafe-mode: false
    max-retries: 3
    lock-lease-time-ms: 5000
    lock-wait-time-ms: 3000

logging:
  level:
    com.invensense.inventory: INFO
